### ISSUE TITLE
Can't get this to run.

### ISSUE THREAD

**Issue by kasturichavan** [hermanussen/sitecore.codegenerator#1]
Hi,

I have exactly followed the steps you have mentioned in Read me. But Cant seem to get this working. I was wondering how does the SampleScriptTemplates.tt know the path for T4Toolbox.tt (I dont have this file in my solution)

Also how will the samplescript point back to my db and know about the template im asking for? Would I have to set the sitecore master db connection somewhere? 

Hope to hear back from you.

**Comment by hermanussen** [comment]
Hi,

Thanks for reaching out.

> how does the SampleScriptTemplates.tt know the path for T4Toolbox.tt (I dont have this file in my solution)

If you've installed the T4 Toolbox Visual Studio extension, then a simple reference to T4Toolbox.tt should work automatically (you can see that's what I've done in SampleScriptTemplates.tt). That's how it's worked for me at least. I think the extension ensures that the path can be resolved to the actual file.

> how will the samplescript point back to my db and know about the template im asking for? Would I have to set the sitecore master db connection somewhere?

If you followed step 5 in the readme correctly, then you've referenced a folder where you keep your serialized data (serialized by hand, with TDS or with older versions of Unicorn) from Sitecore (or follow the steps under 'Using Unicorn's Rainbow format' if you are using Unicorn 3). That's how it works; it generates code based on the serialized data, so you don't need a connection to a DB or Sitecore instance directly.

I understand that setting up this type of code generation can be a bit of work, but it works.

I hope this helps. But feel free to ask if you need any more help!

**Comment by kasturichavan** [comment]
When I try to do Build > Transform all T4 Templates

I get following errors;
![errors](https://cloud.githubusercontent.com/assets/9099244/15476297/398d2e30-20dc-11e6-8fa8-bf075c4b7c7e.PNG)


The fieldOptions is defined in GlassGenerator.cs  which is used by GlassMappedClasstemplate and GlassGenerator needs GlassMappedClassTemplate 

When T4 template tries to generate these cs files. It wont have fieldOptions defined.

**Comment by kasturichavan** [comment]
When I try to do Build> Transform all T4 templates I get these errors.

![errors](https://cloud.githubusercontent.com/assets/9099244/15476433/dc3aa838-20dc-11e6-8adf-202318362875.PNG)

Basically when the T4 template would be generating the class files, for eg: when the GlassMappedClassTemplate is transformed, the fieldOptions defined in GlassGenerator is not yet ready to be accessed since that file includes GlassMappedClassTemplate . So their seems to be dependency between these two files. Wont it lead to Deadlock?

Can you try once by using this dll in a different solution and see if the Build> Transform all T4 templates work for you.?

Thanks

**Comment by amitthakur2014** [comment]
Hi,
I have followed your step as mentioned, In Visual 2015 i am getting the below error, when i right click on SampleScriptTemplates.tt click onCustom Tool.

"Severity Code Description Project File Line Suppression State Error
Compiling transformation: Invalid token 'this' in class, struct, or interface member declaration
SCGlass	C:\Amit\SCGlass\SCGlass\Template\GlassGenerator.tt"	

I am gone through few blog and they mentioning the above error is of VS 2015
https://connect.microsoft.com/VisualStudio/Feedback/Details/2451005

**Comment by BDFurlong** [comment]
@amitthakur2014 You may want to make sure that you don't have an extra line or white space after the final line in GlassGenerator.tt

**Comment by Tyshun** [comment]
@BDFurlong Your suggestion to remove the final line of white space cleared up my issue. Thanks!

**Comment by hermanussen** [comment]
Nice! Thanks guys.
