### ISSUE TITLE
Not all fields are generated when Unicorn/Rainbow uses a shortened path when serializing

### ISSUE THREAD

**Issue by marcduiker** [hermanussen/sitecore.codegenerator#2]
I have an issue where some interfaces are not completely generated (missing properties) because the yml files for template fields are not within the provided serialization folder.

__Example__
Serialization folder in Glass.Generator.tt: `..\..\Serialization\Project X\Feature Y\`
Actual location of yml file which does not get generated: `..\..\Serialization\{GUID}\`

We don't want to change serialization folder in GlassGenerator.tt to `..\..\Serialization\` because too many templates would be included then.

Any suggestions?

**Comment by hermanussen** [comment]
Interesting issue. Obviously, fields that are not included in the serialized data under the path that is provided can not be included in the code generation.

So my first idea would be to change the serialization folder as you suggested. But I get what you're saying; you may not want to generate code for everything.

So, what you may want to do is limit the generated code to a specific set of templates. How you want to do that is entirely up to you.

I have 2 suggestions:

1. Provide sitecore paths that need to be included, as you can see in [SampleScriptTemplates.tt](https://github.com/hermanussen/sitecore.codegenerator/blob/4d15b868193b5f8c1da45df623895f3bb1dc10cb/Sitecore.CodeGenerator.Sample.Glass/Models/SampleScriptTemplates.tt). You don't have to use full paths here... E.g.: /sitecore/templates/folder should work as well.
2. Look at inheriting from the [TemplatesResolver](https://github.com/hermanussen/sitecore.codegenerator/blob/master/Sitecore.CodeGenerator/TemplatesResolver.cs) or [TemplatesResolverRainbow](https://github.com/hermanussen/sitecore.codegenerator/blob/master/Sitecore.CodeGenerator/TemplatesResolverRainbow.cs) class and override GetAllItems(...). You can add any inclusion or exclusion logic you like here.

**Comment by marcduiker** [comment]
Thanks Robin! I provided a higher level serialization path in Glass.Generator.tt and used a specific include path such as you suggested in SampleScriptTemplates.tt. Works like a charm again :).
