### ISSUE TITLE
Can't get the codegeneration to work

### ISSUE THREAD

**Issue by Xuntar** [hermanussen/sitecore.codegenerator#3]
After following all steps as outlined in the readme, I get a few errors when trying to generate the file:
- Compiling transformation: Invalid token 'this' in class, struct, or interface member declaration
- Compiling transformation: 'GeneratedTextTransformation.Write()' must declare a body because it is not marked abstract, extern, or partial
- Compiling transformation: Method must have a return type
- Compiling transformation: Identifier expected

I have the same problem when opening your solution. I'm using VS2015 and the T4tools for that version.

**Comment by Xuntar** [comment]
Ok, I discovered that there were 2 closed issues, one of which mentioned that there shouldn't be an empty line at the end of the GlassGenerator.tt file. That fixed it for me. So many hours wasted...

**Comment by hermanussen** [comment]
Ouch. Sorry about that.

Would have been nice if someone would have submitted a pull request on the first ticket.

In any case, [this commit](https://github.com/hermanussen/sitecore.codegenerator/commit/1b473d6ac660b17f49e044c36cf6d9828540f091) should fix it then.

**Comment by Xuntar** [comment]
No need to apologize! I was just annoyed with myself for not finding it sooner ;-)
Thanks for committing a fix!
